# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82e98e723981c783753135f889c40f7d423b8b3adf8fd01224e0449b33f844ebc20f6a8b437a1fd889574e82d08c92d2df2f1215a9d80e80fddfbe65fb53b40a

test:
  secret_key_base: b0185520c823e9f4e568b5e251c229af691f1a694ed890719eb86927f8e9492ee6198504049d0e995cec8b734a81b05cccc7472a6dda1179e1d5c52a7fa990af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f451dbb53b3053c09de755b08a16756be5a8fd0bd031fe62fc05d1561cd18bb979809aef4e154669fb95e11b32006814472d78710f207eb7a9dc51c65cd96ff4
